#!/bin/bash

GPG_USER="$1"
GPG_SERVER="$2"
HOST="$3"
PORT="$4"

if [ -z "$PORT" ]; then
    echo "Usage: mosh-client-script gpg_user_key gpg_server_key host port"
    echo "Example: mosh-client-script 0x09EA92A2DB6D6082 0x09EA92A2DB6D6082 1.2.3.4 2222"
    exit 1
fi

set -o pipefail

T=`mktemp -d`

trap 'rm -f "$T/reply" "$T/reply.info"; rmdir "$T"' EXIT

echo "$T" | 
    gpg -u "$GPG_USER" -s -r "$GPG_SERVER" -e | 
    ./udpclient 240 250000  "$HOST" "$PORT" | 
    gpg --keyid-format=0xlong > $T/reply 2> $T/reply.info

if [ "$?" != "0" ]; then
    echo Something failed
    exit 1
fi


if grep -q "key $GPG_CHECKSIG_WITH" "$T"/reply.info; then
    :;
else
    echo Reply signed with wrong key
    exit 1
fi

if grep -q "gpg: Good signature from" "$T"/reply.info; then
    :;
else
    echo "Not a good signature"
    exit 1
fi

if grep -q 'MOSH CONNECT ' "$T"/reply; then
    read _1 _2 PORT2 MOSH_KEY <<< "$(grep MOSH\ CONNECT $T/reply)"
    export MOSH_KEY
    rm "$T/reply" "$T/reply.info"
    rmdir "$T"
    exec mosh-client "$HOST" "$PORT2"
else
    echo Malformed reply
    exit 1
fi
